name: First Workflow
on: workflow_dispatch
jobs:
  first-job: #this is custom name not a keyword
    runs-on: ubuntu-latest
    steps: 
      - name: Print greeting
        run: echo "hello world!"
      - name: Print goodbye
        run: echo "Done - bye!"
    
